# Generated by Django 5.1.2 on 2024-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_prayerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
